# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://devhints.io/docker-compose

version: '3'

services:
  djangoapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    expose:
      - 8000
    networks:
      - frontend
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - djangoapp
    networks:
      - frontend
    restart: always

networks:
  frontend:
    driver: bridge



