# start from official image
FROM python:3.10-slim

# create working directory
RUN mkdir -p /pinger
WORKDIR /pinger

# install dependencies
RUN pip install urllib3

# copy wakeup script
COPY wakeup.py /pinger

# run script on startup
CMD ["python", "/pinger/wakeup.py"]

