# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://devhints.io/docker-compose

version: '3'

services:
  
  djangoapp:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - 8000
    networks:
      - frontend
    depends_on:
      - wakeup
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - djangoapp
    networks:
      - frontend
    restart: always

  wakeup:
    build:
      context: .
      dockerfile: wakeup/Dockerfile
    restart: always

networks:

  frontend:
    driver: bridge



