version: '3'

services:
  djangoapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    expose:
      - 8000
    networks:
      - web

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - djangoapp
    networks:
      - web

networks:
  web:
    driver: bridge



