# Docker Hub images can be pushed to a remote host using the local command line: 
# > docker context create remote --docker "host=ssh://user@remotemachine"
# > docker-compose --context remote -f docker-compose.deploy.yml up -d

version: '3'

services:
  djangoapp:
    image: colurw/chess_nn:webapp
    expose:
      - 8000
    networks:
      - nginx_network

  nginx:
    image: colurw/chess_nn:nginx
    ports:
      - 80:80
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge


